# Generated by Django 4.2.4 on 2023-12-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_seccion_descripcion_seccion_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='jornada',
            field=models.CharField(choices=[('duirno', 'Duirno'), ('vespertino', 'Vespertino'), ('mixto', 'Mixto')], default='duirno', max_length=10),
        ),
    ]
