# Generated by Django 4.2.4 on 2023-12-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_usuario_jornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='seccion',
        ),
    ]
