# Generated by Django 4.2.4 on 2023-12-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_stock_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
    ]
