# Generated by Django 4.2.4 on 2023-12-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_stock_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(default='PO-0001', max_length=50, unique=True),
        ),
    ]
