# Generated by Django 4.2.4 on 2023-12-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
