# Generated by Django 4.2.4 on 2023-12-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_productorecibido_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.producto'),
        ),
    ]
